backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\helpers\ConvertCityHelper;
use common\models\City;
use common\models\CitySearch;
use common\models\StatsParamForm;
use toriphes\console\Runner;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use Yii;
use yii\web\Response;
use yii\widgets\ActiveForm;

class SiteController extends Controller
{

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    public function actionIndex()
    {
        $statsParamForm = new StatsParamForm();
        if(Yii::$app->request->isAjax && $statsParamForm->load(Yii::$app->request->post())){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($statsParamForm);
        }
        $statsParamForm->loadDefaultValue();
        return $this->render('index', [
            'statsParamForm' => $statsParamForm,
        ]);
    }

    public function actionLoadData()
    {
        if (!Yii::$app->request->isAjax) {
            throw new BadRequestHttpException('Bad Request');
        }
        Yii::$app->response->format = Response::FORMAT_JSON;
        $count = '';
        $runner = new Runner([
            'yiiscript' => realpath(dirname(Yii::getAlias('@app')) . DIRECTORY_SEPARATOR .  'yii'),
            'phpexec' => PHP_BINDIR . DIRECTORY_SEPARATOR . 'php'
        ]);
        $form = new StatsParamForm();
        $form->load(Yii::$app->request->post());
        if (!$form->validate()) {
            return (["message"=> '0 records loaded']);
        }
        $runner->run('forecast/index ' . $form->start . ' ' . $form->end . ' 2>&1', $count);
        return (["message"=> 'From ' . $form->start . ' to ' . $form->end . ' - ' . $count . ' records loaded']);
    }

    public function actionStats()
    {
        $searchModel = new CitySearch();
        $statsParamForm = new StatsParamForm();

        $statsParamForm->load(Yii::$app->request->get());

        if ($statsParamForm->isEmpty()) {
            $statsParamForm->loadDefaultValue();
        }
        $statsParamForm->validate();

        return $this->render('stats', [
            'dataProvider' => $searchModel->search(Yii::$app->request->queryParams, $statsParamForm),
            'statsParamForm' => $statsParamForm
        ]);
    }

    public function actionHistory($city = '')
    {
        /** @var City $model */
        $model = City::find()->findByName(ConvertCityHelper::convertFromUrl($city))->one();
        if (!$model) {
            throw new NotFoundHttpException('Page not found.');
        }
        return $this->render('history', [
            'forecasts' => $model->getForecasts()->orderBy(['when_created' => SORT_DESC])->all(),
            'city' => $model
        ]);
    }

}

frontend/views/site/_stats_grid.php
<?php

/* @var $this yii\web\View */
/* @var $dataProvider  yii\data\ActiveDataProvider; */

use \yii\helpers\Url;
use \yii\bootstrap\ButtonDropdown;
use  \yii\grid\GridView;
use \common\helpers\ConvertCityHelper;
use \common\helpers\ConvertTemperatureHelper;

?>

<?php
$summPagLayout = '<div class="row"><div class="col-md-6">{summary}</div><div class="col-md-6 text-right">{pager}</div></div>';
?>

<?= GridView::widget([
    'summary' => '<div class="text-muted" style="margin:25px 0 25px;"> Displaying {begin} - {end} of {totalCount} results.</div>',
    'dataProvider' => $dataProvider,
    'layout' => $summPagLayout . '{items}' . $summPagLayout,
    'pager' => [
        'firstPageLabel' => 'First',
        'lastPageLabel' => 'Last',
        'prevPageLabel' => '←',
        'nextPageLabel' => '→'
    ],
    'columns' => [
        'country',
        'city',
        [
            'attribute' => 'maxTemperature',
            'value' => function($data) {
                return $data['maxTemperature'] ? ConvertTemperatureHelper::convertFahrenheitToCelsius($data['maxTemperature']) : null;
            }
        ],
        [
            'attribute' => 'minTemperature',
            'value' => function($data) {
                return $data['minTemperature'] ? ConvertTemperatureHelper::convertFahrenheitToCelsius($data['minTemperature']) : null;
            }
        ],
        [
            'attribute' => 'avgTemperature',
            'value' => function($data) {
                return $data['avgTemperature'] ? ConvertTemperatureHelper::convertFahrenheitToCelsius($data['avgTemperature']) : null;
            }
        ],
        ['class' => 'yii\grid\ActionColumn',
            'template'=>'{view}',
            'buttons'=>[
                'view'=>function ($url, $model) {
                    /** @var $model \common\models\City */
                    $html = ButtonDropdown::widget([
                        'options' => [
                            'class' => 'btn btn-default',
                        ],
                        'label' => 'Action',
                        'dropdown' => [
                            'items' => [
                                [
                                    'label' => 'History',
                                    'url' => Url::to(['site/history', 'city' => ConvertCityHelper::convertToUrl($model['city'])]),
                                    'linkOptions' => ['data-pjax' => 0]
                                ]
                            ]
                        ]
                    ]);
                    return $html;
                },
            ],
        ],
    ]
])?>

frontend/views/site/_stats_param_form.php
<?php

use \yii\widgets\ActiveForm;
use \yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $statsParamForm \common\models\StatsParamForm */

\frontend\assets\DateTimePickerAsset::register($this);

$formName = $statsParamForm->formName();

$form = ActiveForm::begin([
    'id' => $formName,
    'method' => 'get',
    'action' => ['site/stats'],
    'validateOnBlur' => false,
    'options' => ['data-pjax' => true]
]);

?>

<?= $form->field($statsParamForm, 'start', [
    'template' => '{label}
                            <div class="input-group date" id="dtpstart">
                                {input}
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                            {hint}{error}',
    'options' => [
        'class' => 'form-group col-xs-4 col-md-2'
    ]
])
    ->textInput([
        'readonly' => 'readonly',
        'data-date-format' => 'DD.MM.YYYY'
    ])?>

<?= $form->field($statsParamForm, 'end', [
    'template' => '{label}
                            <div class="input-group date" id="dtpend">
                                {input}
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                            {hint}{error}',
    'options' => [
        'class' => 'form-group col-xs-4 col-md-2'
    ]
])
    ->textInput([
        'readonly' => 'readonly',
        'data-date-format' => 'DD.MM.YYYY'
    ])?>

    <div class="form-group col-xs-4 col-md-2">
        <div style="margin-top:25px">
            <?= Html::submitButton('<span class="glyphicon glyphicon-search"></span> Search', ['class' => 'btn btn-success', 'id' => $formName . 'submit']) ?>
        </div>
    </div>

<?php ActiveForm::end() ?>

<?php
$script = "
$(function () {
    $('#dtpstart').datetimepicker({ignoreReadonly: true});
    $('#dtpend').datetimepicker({ignoreReadonly: true});
});
$('#" . $formName . "').on('beforeSubmit', function(e){
    e.preventDefault();
    var form = $('#" . $formName . "');
    var start = form.find('input[name=\"" . $formName . "[start]\"]').val();
    var end = form.find('input[name=\"" . $formName . "[end]\"]').val();
    var url= form.attr('action') + '?" . $formName . "[start]=' + start + '&" . $formName . "[end]=' + end;
    $.pjax.reload({
        history: false,
        url: url, 
        container: '#pjaxstats'
    });
    return false;
})
";
$this->registerJs($script, $this::POS_END);

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/history.php
<?php

/* @var $this yii\web\View */
/** @var $forecasts  */
/** @var $city \common\models\City */

use \yii\helpers\Url;
use \common\helpers\ConvertTemperatureHelper;

$headerTitle = 'History of ' . $city->name . ' (' . $city->country->name . ')';
$this->title = 'Forecast - ' . $headerTitle;

$this->params['breadcrumbs'][] = ['label' => 'Statistics', 'url' => Url::to(['site/stats'])];
$this->params['breadcrumbs'][] = $city->name;
?>

<div class="panel panel-default">
    <div class="panel-heading">
        <?= $headerTitle ?>
    </div>
    <div class="panel-body">
        <?php
        $cell = 0;
        $start = '';
        foreach ($forecasts as $item) {
            if ($cell == 0) {
                echo '<div class="row">';
            }
            $header = date('F d, Y', $item['when_created']);
            if (!$start) {
                $start = $header;
                $cell++;
                echo '<div class="col-xs-3">';
                echo '<p><strong>' . $start . '</strong></p>';

            }
            if ($start != $header) {
                $start = $header;
                echo '</div>'; // close col-xs-3
                if ($cell == 4) {
                    $cell = 0;
                    echo '</div>'; // close row
                    echo '<div class="row">';
                }
                $cell++;
                echo '<div class="col-xs-3">';
                echo '<p><strong>' . $start . '</strong></p>';
            }
            echo '<p>' . date('H:i:s', $item['when_created']) . ' ' . ConvertTemperatureHelper::convertFahrenheitToCelsius($item['temperature']) . ' &#8451</p>';
        }
        echo '</div>'; //close col-xs-3
        echo '</div>'; //close row
        ?>
    </div>
</div>

frontend/views/site/index.php
<?php

use \yii\widgets\ActiveForm;
use \yii\helpers\Html;

/* @var $statsParamForm \common\models\StatsParamForm */

\frontend\assets\DateTimePickerAsset::register($this);

$this->title = 'Forecasts - statistics';
$formName = $statsParamForm->formName();
?>

<div class="site-index">

    <div class="panel panel-default">
        <div class="panel-heading">
            Load new data
        </div>
        <div class="panel-body">

            <?php $form = ActiveForm::begin([
                'id' => $formName,
                'method' => 'post',
                'action' => ['site/load-data'],
                'validateOnBlur' => false,
                'enableAjaxValidation' => true,
                'validationUrl' => ['site/index']
            ]); ?>

            <?= $form->field($statsParamForm, 'start', [
                'template' => '{label}
                            <div class="input-group date" id="dtpstart">
                                {input}
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                            {hint}{error}',
                'options' => [
                    'class' => 'form-group col-xs-4 col-md-2'
                ]
            ])
                ->textInput([
                    'readonly' => 'readonly',
                    'data-date-format' => 'DD.MM.YYYY'
                ])?>

            <?= $form->field($statsParamForm, 'end', [
                'template' => '{label}
                            <div class="input-group date" id="dtpend">
                                {input}
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                 </span>
                            </div>
                            {hint}{error}',
                'options' => [
                    'class' => 'form-group col-xs-4 col-md-2'
                ]
            ])
                ->textInput([
                    'readonly' => 'readonly',
                    'data-date-format' => 'DD.MM.YYYY'
                ])?>

            <div class="form-group col-xs-4 col-md-2">
                <div style="margin-top:25px">
                    <?= Html::submitButton('<span class="glyphicon glyphicon-search"></span> Load', ['class' => 'btn btn-success', 'id' => $formName . 'submit']) ?>
                </div>
            </div>

            <?php ActiveForm::end() ?>

            <?php
            $script = "
$(function () {
    $('#dtpstart').datetimepicker({ignoreReadonly: true});
    $('#dtpend').datetimepicker({ignoreReadonly: true});
});
$('#" . $formName . "').on('beforeSubmit', function(e){
    e.preventDefault();
    var form = $(this);
    var submitButton = $('#" . $formName . "submit');
    $('#messageBox').text('').addClass('hidden');
    submitButton.text('Wait...').prop('disabled', true).removeClass('btn-success').addClass('btn-warning');
    $.ajax({
            type: form.attr('method'),
            dataType: 'json',
            url: form.attr('action'),
            data: form.serialize(),
            success: function(result) {
                console.log(JSON.stringify(result.message));              
                $('#messageBox').text(JSON.stringify(result.message)).removeClass('hidden');
                resetData();           
            },
            error: function(result) {
                resetData();
                alert('Error. Try again later');
            }
        });
    return false;
})
$('#" . $formName . "').on('beforeValidate', function(e){
    $('#messageBox').text('').addClass('hidden');
})
function resetData()
{
    var submitButton = $('#" . $formName . "submit');
    submitButton.text('Load').prop('disabled', false).addClass('btn-success').removeClass('btn-warning');
}
";
            $this->registerJs($script, $this::POS_END);
            ?>
        </div>
    </div>
    <div class="alert alert-info hidden" id="messageBox">

    </div>
</div>

frontend/views/site/stats.php
<?php

/* @var $this yii\web\View */
/* @var $dataProvider  yii\data\ActiveDataProvider; */
/* @var $statsParamForm \common\models\StatsParamForm */

$this->title = 'Forecast - Statistics';
$this->params['breadcrumbs'][] = 'Statistics';

use yii\widgets\Pjax;

Pjax::begin([
    'enablePushState' => false,
    'id' => 'pjaxstats'
]);

?>

    <div class="panel panel-default">
        <div class="panel-heading">
            Search
        </div>
        <div class="panel-body">
            <?= $this->render('_stats_param_form', ['statsParamForm' => $statsParamForm])?>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-body">
            <?= $this->render('_stats_grid', ['dataProvider' => $dataProvider])?>
        </div>
    </div>

<?php

Pjax::end();